on:
  push:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  every-minute-job:
    runs-on: ubuntu-latest
    steps:
      - name: Log Time
        run: 'echo "This job runs every minute! Current time: $(date)"'
