name: API Trigger

on:
  repository_dispatch:

jobs:
  greet:
    if: ${{ startsWith(github.event.client_payload.name, 'Ant') }}
    runs-on: ubuntu-latest
    steps:
      - name: Show Name
        run: echo "${{ github.event.client_payload.name }}"
