name: API Trigger

on:
  repository_dispatch:

jobs:
  greet:
    if: ${{ startsWith(github.event.client_payload.name, 'Ant') }}
    runs-on: ubuntu-latest
    steps:
      - name: Show Name
        run: |
            echo "Name ${{ github.event.client_payload.name }} and actor is ${{ github.actor }}"
            echo "Action = ${{github.action}}"
