name: API Trigger

on:
  repository_dispatch:

jobs:
  greet:
    if: ${{ github.event.client_payload.name == 'Gosha' }}
    runs-on: ubuntu-latest
    steps:
      - name: Show Name
        run: echo "${{ github.event.client_payload.name }}"
